# Use postgres/example user/password credentials
version: '3.8'

services:

  pg_db:
    container_name: pgdb_container
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=saruman
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes: 
      - ./db_data:/var/lib/postgresql/data
      # - pgdb_volume:/var/lib/postgresql/data

  pg_admin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=todo@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80

# volumes:
#   pgdb_volume:
#     driver: local
